version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: keepassxc-browser:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: develop
    upstream: develop        # Required. Can be a branch in the same forked repo.
    mergeMethod: merge
    assignees:              # Optional
      - mko-x
    reviewers:              # Optional
      - mko-x
label: ":arrow_heading_down: pull"  # Optional
